apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- deployment_env.yaml
- ingress.yaml

namespace: gitops-demo-dev

nameSuffix: -dev

labels:
- includeSelectors: true
  pairs:
    env: dev

images:
- name: pentago/gitops-demo-backend
  newName: pentago/gitops-demo-backend
  newTag: 8bbe273
- name: pentago/gitops-demo-frontend
  newName: pentago/gitops-demo-frontend
  newTag: 670658e
