apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

patches:
- resource_requests_limits.yaml
- deployment_env.yaml
- frontend-container-security-context.yaml
- backend-container-security-context.yaml
- ingress.yaml
- deployment_hpa.yaml

namespace: gitops-demo-prod

nameSuffix: -prod

labels:
- pairs:
    env: prod
  includeSelectors: true

images:
- name: pentago/gitops-demo-backend
  newName: pentago/gitops-demo-backend
  newTag: 10b202a
- name: pentago/gitops-demo-frontend
  newName: pentago/gitops-demo-frontend
  newTag: 670658e
