apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx.conf
data:
  nginx.conf: |
    worker_processes auto;
    worker_rlimit_nofile 8192;
    error_log /var/log/nginx/error.log warn;
    pid /tmp/nginx.pid;

    events { worker_connections 8000; }

    http {
        aio threads;
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path /tmp/proxy_temp_path;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
        include /etc/nginx/mime.types;
        keepalive_timeout 20s;
        sendfile on;
        tcp_nopush on;
        open_file_cache max=1000 inactive=20s;
        open_file_cache_valid 30s;
        open_file_cache_min_uses 2;
        open_file_cache_errors on;
        client_max_body_size 100m;
        client_body_buffer_size 50m;
        default_type application/octet-stream;
        charset utf-8;
        charset_types
            text/css
            application/javascript
            text/javascript
            application/json
            application/manifest+json
            text/plain
            text/xml
            application/rss+xml
            text/markdown
            text/vnd.wap.wml
            text/calendar
            text/x-component
            text/vcard
            text/cache-manifest
            text/vtt;
        log_format main '$remote_addr [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;

        server {
            listen 8080;
            server_name localhost;
            root /var/www/html;
            index index.php;

            location ~* /\. { deny all; }
            location ~* \.(git|bak|conf|dist|log|psd|sh|sql|swp).*$ { deny all; }
            location ~* \.(ico|css|js|gif|jpe?g|png|svg|woff2)(\?[0-9]+)?$ { log_not_found off; access_log off; }
            location ~* (robots.txt|favicon.ico)$ { log_not_found off; access_log off; }

            location / { try_files $uri $uri/ /index.php; }

            location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                if (!-f $document_root$fastcgi_script_name) { return 404; }
                include fastcgi.conf;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_pass 127.0.0.1:9000;
            }

            location /nginxstatus {
                stub_status;
                allow 127.0.0.1;
                access_log off;
            }

            location ~ ^/(phpfpmstatus|healthz)$ {
                fastcgi_pass 127.0.0.1:9000;
                include fastcgi.conf;
                allow 127.0.0.1;
                access_log off;
            }
        }
    }